dist: xenial
sudo: required
install: true  # skips unnecessary "gradle assemble" install step

services:
  - docker

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - DOCKER_USERNAME: napstr
    - secure: "lK0CIWtNFURU1zQ3pzklrXehbJPLJGuXKkNv6cHuJ74LBfQVdczehVowijD6pAiNnyr1WHpYnQyyhqBUfusTP9OJaM5aXfmvtZCQa0lC5fzuXHSfX8ua5rU9bv92Wo3RQsSL3blbtBOreeqCMq98oUJLv+DBPUwN3GafdEeMg6IcVB09rsIong4weZtpbvFrAa5qhX64jGGaB+fyt0OVhLfrkj1A7+94aZBLjhrDsYg4d01k0yAjuoqjmSRdf1bxMNK93n24GtU9z8SuRwjQcY0LtNPIpp3WHiBEqelyWJyF7vftsiEkX4x24TyQe655D3A1C4ZxyvlMq8wvdznilgSuJpi5y0UIhcUHPHEqBkl3iqdNFFvMg2P+KUfiv9V7Q8GOxAvk9Zn4J1+AWZtq1T1y0zu2IZB+xE2hK0OgNUe/dY7Dc1Olx24HP/r57NDwn7JwZOC6e/Dk5jUKFEeRe1N7kvKvsshzEGg/aFrSBXTy8sihB9UvQ6aIfgGYn5dJFsGeUr6Ox/8ggcau3Amvq8e/CkCH4qG9un/IuGeOI+NbhrgwQhFyqjlJaI8AExcFyYK0wjGxdKfRbUKLTfwe5cqOIRevxxcy7fW9MXVuWh6Wj6i2E72iqPl7DOWbRXqkZw4kZ+XqkqxMmZAIGhAh83L+hJES5FoYfrR48wkEpsg="

language: java

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle/wrapper"
    - "$HOME/.gradle/caches"

stages:
  - build & publish

jobs:
  fast_finish: true
  include:
    - stage: build & publish
      jdk: openjdk11
      script:
        - java -Xmx32m -version
        - ./gradlew build --info
        - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
        - echo $IMAGE_TAG
        - IMAGE_NAME=$DOCKER_USERNAME/icu:$IMAGE_TAG
        - docker build --tag "$IMAGE_NAME" .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
        - docker push $IMAGE_NAME
        - docker logout
