version: '3.6'
services:

  db:
    image: napstr/icu-postgres:11
    restart: always
    volumes:
      - ./postgres-data/11/data:/var/lib/postgresql/data

  bot:
    image: napstr/icu:master
    restart: on-failure:3
    depends_on:
      - db
    volumes:
      - ./sneaky.yaml:/opt/icu/sneaky.yaml
      - ./logs:/opt/icu/logs
      - ./logs/gc:/opt/icu/logs/gc
    entrypoint:
      - java
      - -Xmx1024m
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=emergencydump.hprof
      - -Xlog:gc*:logs/gc/gc-%t.log::filesize=1048576   #1gb
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:+UseStringDeduplication
      - -jar
      - icu.jar
