version: '3.6'
services:

  db:
    image: napstr/poggres:14
    restart: always
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./postgres-data/13/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=icu
      # See https://github.com/napstr/poggres#env-vars
      - ROLE=icu
      - PASSWORD=icu
      - DB=icu
      - EXTENSIONS=hstore
