sentry:
  dsn: ""
  logging.enabled: false
  in-app-includes:
    - "space.npstr"
    - "dev.capybaralabs"
  logging:
    minimum-event-level: warn

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/icu?user=icu&password=icu
  main:
    lazy-initialization: false
  jpa:
    hibernate:
      ddl-auto: update
