version: '3.6'
services:

  db:
    image: napstr/poggres:16
    restart: always
    volumes:
      - ./postgres-data/16/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=icu
      # See https://github.com/napstr/poggres#env-vars
      - ROLE=icu
      - PASSWORD=icu
      - DB=icu
      - EXTENSIONS=hstore

  bot:
    image: napstr/icu:master
    restart: on-failure:3
    depends_on:
      - db
    volumes:
      - ./sneaky.yaml:/opt/icu/sneaky.yaml
      - ./logs:/opt/icu/logs
      - ./logs/gc:/opt/icu/logs/gc
    ports:
      - 127.0.0.1:5006:5005   # Remote debug
    entrypoint:
      - java
      - -Xmx1024m
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=emergencydump.hprof
      - -Xlog:gc*:logs/gc/gc-%t.log::filesize=1048576   #1gb
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:+UseStringDeduplication
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - -jar
      - icu.jar
