name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@e2c57acffb2c9aa5a8dc6eda2bbae0b6e495bd4c # v1.0.3

      - name: Set up env
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        # Build number is increased by 100 due to legacy reasons from previous CI systems
        run: |
          echo $GITHUB_RUN_NUMBER
          BUILD_NUMBER=$((100 + $GITHUB_RUN_NUMBER))
          echo $BUILD_NUMBER
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> "$GITHUB_ENV"

          IMAGE_TAG=$(echo $GITHUB_REF | sed -e 's+refs/heads/++g' | sed -e 's+/+_+g')
          echo $IMAGE_TAG
          echo "IMAGE_NAME=${{ env.DOCKER_USERNAME }}/icu:$IMAGE_TAG" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup JDK
        uses: actions/setup-java@3bc31aaf88e8fc94dc1e632d48af61be5ca8721c # v2.3.0
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Print JDK info
        run: java -Xmx32m --version

      - name: Gradle Build
        uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf # v1.10
        with:
          arguments: build --info

      - name: Docker Build
        run: docker build -t "${{ env.IMAGE_NAME }}" .

      - name: Docker Push
        run: docker push "${{ env.IMAGE_NAME }}"
